### ISSUE TITLE
need PR

### ISSUE THREAD

**Issue by tunnckoCore** [jstransformers/jstransformer-microtemplate#1]
`ReferenceError: _merge is not defined`

https://github.com/xudafeng/microtemplate/blob/master/lib/microtemplate.js#L117

**Comment by RobLoach** [comment]
If you push what you have, then we could help out in debugging.

**Comment by tunnckoCore** [comment]
It would be just like 

``` js
exports.compile = microtemplate.compile
exports.render = microtemplate.render
```

but not works by default, so first PR there needed.

**Comment by RobLoach** [comment]
https://github.com/xudafeng/microtemplate/pull/1

**Comment by RobLoach** [comment]
Can you push up what you have, if you've done anything on this? We can fix in pull requests. Otherwise, it might be worth it to delete this repository.

**Comment by tunnckoCore** [comment]
I dont have nothing, cuz it not works. Yea, it would be better to delete it. Also I remember there have one more engine called micro-template and it can be confusing if we have them both.

**Comment by RobLoach** [comment]
> I remember there have one more engine called micro-template and it can be confusing if we have them both.

As long as it matches the npm package name, then there will not be any confusion.

> I dont have nothing, cuz it not works.

We can reference the branch for this pull request: https://github.com/xudafeng/microtemplate/pull/1

**Comment by tunnckoCore** [comment]
:+1:
